apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-dashboard-reactjs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-dashboard-reactjs-web
  template:
    metadata:
      labels:
        app: solar-dashboard-reactjs-web
    spec:
      containers:
        - name: solar-dashboard-reactjs-web
          image: public.ecr.aws/s6y5a7e8/voucher-app:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-k8s-service
spec:
  selector:
    app: solar-dashboard-reactjs-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
